### ISSUE TITLE
分类目录出错

### ISSUE THREAD

**Issue by UFOAlastor** [jiansing/gridea-theme-inlineamp#1]
当点击进入分类目录后，在不同的目录下，侧边栏显示的分类目录是不同的，而且当分类数量超过两个后，会出现重复显示的bug。
我非常喜欢这个主题，如果能够越来越完善就好了:D

**Comment by jiansing** [comment]
已经修复，请更新到最新版本
https://github.com/jiansing/gridea-theme-inlineamp/releases

**Comment by UFOAlastor** [comment]
非常感谢您如此迅速的修复这个bug，我近来尝试为这个主题添加Valine留言系统，并且取得了成功，不知您是否有意了解一下，并将其加入这个主题中，为更多人带去便利？
您可以参考我的博客上的方法：https://ufoalastor.github.io/vHn2S1tFt/








&nbsp;





------------------&nbsp;Original&nbsp;------------------

**Comment by UFOAlastor** [comment]
哦，我非常高兴您已经解决了侧边栏的问题，现在它在我的文章内也可以正常显示了！
但是，很不幸的，又出现了新的问题



这个问题在您更新前后的版本中都会出现，我不知道是否是我本人错误的操作造成这样的结果，但是我尝试过解决，都无法成功，不得不求助于您:D


如图所示，会出现标签重复的问题，但是在Gridea本地的标签一栏中并没有重复的标签。






&nbsp;





------------------&nbsp;Original&nbsp;------------------

**Comment by jiansing** [comment]
1）你的blog似乎已经不存在标签重复的问题，如果还遇到问题可以再来提issue
2）你手动添加Valine的方式完全可以正常使用，但无法通过AMP验证。
对于Valine评论系统，我曾经考虑过，但是Valine目前还没有支持AMP的解决方案。
InlineAMP主题（[原主题](https://github.com/justid/InlineAMP)）最重要的核心产品/技术设定就是完全[使用AMP技术构建主题](https://hhacker.com/%e7%9c%9f%e9%a6%99%ef%bc%8c30%e5%a4%a9%e5%81%9a%e4%b8%80%e5%a5%97wordpress%e4%b8%bb%e9%a2%98%ef%bc%88%e7%ac%ac1%e5%a4%a9%ef%bc%89%ef%bc%9a%e5%9f%ba%e7%a1%80%e6%a1%86%e6%9e%b6%e6%90%ad%e5%bb%ba.html)，本主题会尽量保留原作者的基本设定，同时会根据Gridea平台的特点在功能上有所选择。
鉴于以上考量，在没有切实可行的完全兼容AMP的方法之前，不会将GITALK、Valine评论系统加入本主题。
当然如果不在乎是否为纯AMP，你仍然可以随意改造本主题
有其他功能需求可以另外提一个issue
