### ISSUE TITLE
文章封面的时间显示错误

### ISSUE THREAD

**Issue by UFOAlastor** [jiansing/gridea-theme-inlineamp#2]
https://i.niupic.com/images/2020/04/06/7hAS.png
详情看图片。
我已经更新了4.5号的最新版本，然而并不能解决这个问题。为避免偶然性，我将旧版本的文件删除后，再复制上新版本的文件。我看到制作者的博客中时间能显示正常（显示当前时间和发布时间，我认为是正常状态），但是我的博客中，发布时间为18年的文章却显示2020,2019,2018三个时间。
另外我希望只显示例如2018这个发布时间，这就足够了:D

**Comment by jiansing** [comment]
已修复
