### ISSUE TITLE
“当前主题暂无自定义配置”

### ISSUE THREAD

**Issue by Lparksi** [jiansing/gridea-theme-inlineamp#3]
正确配置后显示 当前主题暂无自定义配置
![GyTDbT.png](https://s1.ax1x.com/2020/04/06/GyTDbT.png)
![GyT2G9.png](https://s1.ax1x.com/2020/04/06/GyT2G9.png)
注： js代码为百度统计

**Comment by jiansing** [comment]
测试了最新的v1.2.0版本，开启百度统计，并没有复现问题
你可以检查一下主题目录下的[config.json](https://github.com/jiansing/gridea-theme-inlineamp/blob/master/inlineamp/config.json)文件是否存在，或者试试重新安装主题

**Comment by Lparksi** [comment]
已解决，感谢
