### ISSUE TITLE
disqus代码URL无法更新

### ISSUE THREAD

**Issue by Tony1026** [jiansing/gridea-theme-inlineamp#6]
在gitee page上传了页面，也更新了代码，但是页面上显示的链接是博客页面本身的链接

**Comment by jiansing** [comment]
请检查一下「Disqus 代码 URL」这一项设置有没有保存（保存后在 gridea/config/theme.inlineamp.config.json 文件里面能找到 disqusurl ）

**Comment by Tony1026** [comment]
有保存

**Comment by Tony1026** [comment]
在预览的时候就显示的博客链接

**Comment by jiansing** [comment]
我好像知道你的问题了，你需要前往 Disqus 管理后台的设置里面，点击 Advanced，在 Trusted Domains 那里添加你的域名。
我使用 [1.2.0 版本](https://github.com/jiansing/gridea-theme-inlineamp/releases/tag/v1.2.0)并没有复现这个 bug，Gridea 的其他主题也有过设置无法生效的问题，如果上述方法无法解决，建议删除主题后重新安装。
正常情况应该能在 theme.inlineamp.config.json 文件里面找到这个
![452HZ51krE](https://user-images.githubusercontent.com/19361673/80105323-08b1e700-85ab-11ea-9445-af23b46bc02a.png)

**Comment by Tony1026** [comment]
好像还是不行，我重装一下再试试

**Comment by Tony1026** [comment]
需要对gridea本身的评论配置进行修改吗

**Comment by jiansing** [comment]
Gridea 本身的评论配置里只需要平台选择 Disqus，并打开显示评论的开关就可以了

**Comment by Tony1026** [comment]
下面api、shortname都不需要吗

**Comment by Tony1026** [comment]
本地设置如上，都是正常的

但是预览出来的结果是博客的原网页

**Comment by jiansing** [comment]
Gridea 自带的评论配置中平台选择 Disqus，打开显示评论，在主题的**自定义配置**里填好 Disqus 代码 URL 和 Disqus 子域就可以了。
如果不行的话，将 [disqus.ejs](https://github.com/jiansing/gridea-theme-inlineamp/blob/v1.2.0/inlineamp/templates/includes/disqus.ejs) 文件中的 <%= site.customConfig.disqus %> 替换为你 disqus 代码 的 URL。

**Comment by jiansing** [comment]
建议使用 [1.2.1](https://github.com/jiansing/gridea-theme-inlineamp/releases/tag/v1.2.1) 版本，并更新你的 HTML 文件代码：https://gist.github.com/jiansing/b95828a1d288965f3d3d6ba7cd260bc1

**Comment by Tony1026** [comment]
能用了，感谢
